SUPABASE_URL = "https://gxaovuzncnihensuvvpt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4YW92dXpuY25paGVuc3V2dnB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTE4MjQsImV4cCI6MjA2MTU2NzgyNH0.rbxKWSUU0E0jTxpVRId4OuziIIKr5anm3-KjVk7c9Ts"
